json.first_name contact.first_name
json.last_name contact.last_name
json.email contact.email
json.phone_number contact.phone_number
json.address contact.address
json.latitude contact.latitude
json.longitude contact.longitude
json.created_at contact.created_at
json.updated_at contact.updated_at
